name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Verify Git installed
      run: git --version
    - name: Configure committer
      run: git config --global user.email "you@example.com" && git config --global user.name "unknown"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=1 cargo test --verbose
    - name: Clippy
      run: cargo clippy -- -D warnings
